# Generated by Django 4.1 on 2022-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='icono',
            field=models.CharField(default='fa-glass', max_length=50),
        ),
    ]
