# Generated by Django 4.1 on 2022-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_blog_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icono',
            field=models.CharField(default='fa-grav', max_length=50),
        ),
    ]
