# Generated by Django 4.1 on 2022-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_blog_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icono',
            field=models.CharField(default='fa-hand-point-right', max_length=50),
        ),
    ]
